import 'dart:io';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:device_info_plus/device_info_plus.dart';
import 'package:flutter/foundation.dart';
import '../models/login_history_model.dart';

class LoginHistoryService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final DeviceInfoPlugin _deviceInfo = DeviceInfoPlugin();

  /// Record a login event
  Future<void> recordLogin(String userId, {String? city, String? country}) async {
    try {
      final deviceInfo = await _getDeviceInfo();
      final location = _formatLocation(city, country);

      final history = LoginHistoryModel(
        id: '', // Generated by Firestore
        userId: userId,
        timestamp: DateTime.now(),
        device: deviceInfo,
        location: location,
      );

      await _firestore
          .collection('users')
          .doc(userId)
          .collection('login_history')
          .add(history.toMap());
    } catch (e) {
      debugPrint('Error recording login history: $e');
    }
  }

  /// Get login history stream
  Stream<List<LoginHistoryModel>> getLoginHistory(String userId) {
    return _firestore
        .collection('users')
        .doc(userId)
        .collection('login_history')
        .orderBy('timestamp', descending: true)
        .snapshots()
        .map((snapshot) {
      return snapshot.docs
          .map((doc) => LoginHistoryModel.fromFirestore(doc))
          .toList();
    });
  }

  Future<String> _getDeviceInfo() async {
    try {
      if (kIsWeb) {
        final WebBrowserInfo webInfo = await _deviceInfo.webBrowserInfo;
        return '${webInfo.browserName.name} on ${webInfo.platform}';
      } else if (Platform.isAndroid) {
        final AndroidDeviceInfo androidInfo = await _deviceInfo.androidInfo;
        return '${androidInfo.manufacturer} ${androidInfo.model}';
      } else if (Platform.isIOS) {
        final IosDeviceInfo iosInfo = await _deviceInfo.iosInfo;
        return '${iosInfo.name} ${iosInfo.systemName} ${iosInfo.systemVersion}';
      } else if (Platform.isLinux) {
         final LinuxDeviceInfo linuxInfo = await _deviceInfo.linuxInfo;
         return '${linuxInfo.name} ${linuxInfo.versionId}';
      } else if (Platform.isMacOS) {
        final MacOsDeviceInfo macInfo = await _deviceInfo.macOsInfo;
        return '${macInfo.model} ${macInfo.osRelease}';
      } else if (Platform.isWindows) {
        final WindowsDeviceInfo windowsInfo = await _deviceInfo.windowsInfo;
        return 'Windows ${windowsInfo.majorVersion}.${windowsInfo.minorVersion}';
      }
      return 'Unknown Device';
    } catch (e) {
      return 'Unknown Device';
    }
  }

  String _formatLocation(String? city, String? country) {
    if ((city == null || city.isEmpty) && (country == null || country.isEmpty)) {
      return 'Unknown Location';
    }
    if (city != null && city.isNotEmpty && country != null && country.isNotEmpty) {
      return '$city, $country';
    }
    return city ?? country ?? 'Unknown Location';
  }
}
