import 'dart:io';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/login_history_model.dart';

class LoginHistoryService {
  final FirebaseFirestore _firestore;

  LoginHistoryService({FirebaseFirestore? firestore})
      : _firestore = firestore ?? FirebaseFirestore.instance;

  /// Fetch login history for a user
  Future<List<LoginHistoryModel>> getLoginHistory(String userId) async {
    try {
      final snapshot = await _firestore
          .collection('users')
          .doc(userId)
          .collection('login_history')
          .orderBy('timestamp', descending: true)
          .limit(50) // Limit to last 50 logins
          .get();

      return snapshot.docs
          .map((doc) => LoginHistoryModel.fromFirestore(doc))
          .toList();
    } catch (e) {
      // In a real app, use a logger
      print('Error fetching login history: $e');
      return [];
    }
  }

  /// Record a new login event
  Future<void> recordLogin(String userId, {String? location}) async {
    try {
      String deviceInfo = 'Unknown Device';
      try {
        if (Platform.isAndroid) {
          deviceInfo = 'Android';
          // Operating system version can be verbose, so maybe just 'Android' is safer if we want cleaner UI,
          // but 'Android <version>' is better.
          deviceInfo = 'Android ${Platform.operatingSystemVersion.split(' ')[0]}'; // Simple version
        } else if (Platform.isIOS) {
          deviceInfo = 'iOS ${Platform.operatingSystemVersion}';
        } else if (Platform.isMacOS) {
          deviceInfo = 'macOS ${Platform.operatingSystemVersion}';
        } else if (Platform.isWindows) {
          deviceInfo = 'Windows ${Platform.operatingSystemVersion}';
        } else if (Platform.isLinux) {
          deviceInfo = 'Linux';
        }
      } catch (e) {
        // Platform check might fail in some environments (e.g. web if not guarded, though this file imports dart:io)
        deviceInfo = 'Unknown Platform';
      }

      String finalLocation = location ?? 'Unknown';
      if (finalLocation == 'Unknown') {
        try {
          final userDoc = await _firestore.collection('users').doc(userId).get();
          if (userDoc.exists) {
            final data = userDoc.data();
            if (data != null) {
              final city = data['city'] as String?;
              final country = data['country'] as String?;
              if (city != null && city.isNotEmpty && country != null && country.isNotEmpty) {
                finalLocation = '$city, $country';
              } else if (city != null && city.isNotEmpty) {
                finalLocation = city;
              } else if (country != null && country.isNotEmpty) {
                finalLocation = country;
              }
            }
          }
        } catch (_) {
          // Ignore error fetching user location
        }
      }

      final history = LoginHistoryModel(
        id: '', // Generated by Firestore
        userId: userId,
        timestamp: DateTime.now(),
        location: finalLocation,
        deviceInfo: deviceInfo,
      );

      await _firestore
          .collection('users')
          .doc(userId)
          .collection('login_history')
          .add(history.toMap());
    } catch (e) {
      print('Error recording login history: $e');
      // Fail silently to not disrupt the login flow
    }
  }
}
