import 'dart:io';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:chingu/models/moment_model.dart';
import 'package:chingu/services/storage_service.dart';

class MomentService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final StorageService _storageService = StorageService();

  /// Create a new moment
  Future<void> createMoment({
    required String userId,
    required String userName,
    String? userAvatar,
    required String content,
    File? imageFile,
  }) async {
    String? imageUrl;

    if (imageFile != null) {
      final String path = 'moments/$userId/${DateTime.now().millisecondsSinceEpoch}.jpg';
      final task = _storageService.uploadFile(imageFile, path);
      // Wait for upload to complete
      final snapshot = await task;
      // Get download URL
      imageUrl = await snapshot.ref.getDownloadURL();
    }

    final moment = MomentModel(
      id: '', // ID will be generated by Firestore
      userId: userId,
      userName: userName,
      userAvatar: userAvatar,
      content: content,
      imageUrl: imageUrl,
      createdAt: DateTime.now(),
    );

    await _firestore.collection('moments').add(moment.toMap());
  }

  /// Get moments for a specific user
  Stream<List<MomentModel>> getUserMoments(String userId) {
    return _firestore
        .collection('moments')
        .where('userId', isEqualTo: userId)
        .orderBy('createdAt', descending: true)
        .snapshots()
        .map((snapshot) {
      return snapshot.docs.map((doc) {
        return MomentModel.fromMap(doc.data(), doc.id);
      }).toList();
    });
  }

  /// Delete a moment
  Future<void> deleteMoment(String momentId) async {
    await _firestore.collection('moments').doc(momentId).delete();
  }
}
