import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:chingu/models/models.dart';

class MomentService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  CollectionReference get _momentsCollection => _firestore.collection('moments');

  /// Toggles like status for a moment.
  ///
  /// [momentId] The ID of the moment.
  /// [userId] The ID of the user liking/unliking.
  /// [isLiked] The new like status (true if liking, false if unliking).
  Future<void> toggleLike(String momentId, String userId, bool isLiked) async {
    try {
      await _firestore.runTransaction((transaction) async {
        final momentRef = _momentsCollection.doc(momentId);

        // Use a subcollection 'likes' to store likes to avoid document size limits if many likes
        // and to easily query if a user liked a moment.
        final likeRef = momentRef.collection('likes').doc(userId);
        final likeDoc = await transaction.get(likeRef);

        if (isLiked) {
          if (!likeDoc.exists) {
             transaction.set(likeRef, {'createdAt': FieldValue.serverTimestamp()});
             transaction.update(momentRef, {'likeCount': FieldValue.increment(1)});
          }
        } else {
          if (likeDoc.exists) {
            transaction.delete(likeRef);
            transaction.update(momentRef, {'likeCount': FieldValue.increment(-1)});
          }
        }
      });
    } catch (e) {
      throw Exception('Failed to toggle like: $e');
    }
  }

  /// Checks if a user liked a moment.
  Future<bool> hasLiked(String momentId, String userId) async {
    final doc = await _momentsCollection.doc(momentId).collection('likes').doc(userId).get();
    return doc.exists;
  }

  /// Gets comments for a moment.
  Stream<List<CommentModel>> getComments(String momentId) {
    return _momentsCollection
        .doc(momentId)
        .collection('comments')
        .orderBy('createdAt', descending: true)
        .snapshots()
        .map((snapshot) {
      return snapshot.docs.map((doc) {
        return CommentModel.fromMap(doc.data(), doc.id);
      }).toList();
    });
  }

  /// Adds a comment to a moment.
  Future<void> addComment(String momentId, String userId, String content) async {
    try {
      // Need user details to store in comment for display
      final userDoc = await _firestore.collection('users').doc(userId).get();
      final userData = userDoc.data();
      final String userName = userData?['name'] ?? 'Unknown';
      final String? userAvatar = userData?['avatarUrl'];

      final comment = CommentModel(
        id: '', // Generated by Firestore
        momentId: momentId,
        userId: userId,
        userName: userName,
        userAvatar: userAvatar,
        content: content,
        createdAt: DateTime.now(),
      );

      await _firestore.runTransaction((transaction) async {
        final momentRef = _momentsCollection.doc(momentId);
        final commentsRef = momentRef.collection('comments').doc();

        final commentMap = comment.toMap();
        commentMap['createdAt'] = FieldValue.serverTimestamp();

        transaction.set(commentsRef, commentMap);
        transaction.update(momentRef, {'commentCount': FieldValue.increment(1)});
      });
    } catch (e) {
      throw Exception('Failed to add comment: $e');
    }
  }

  /// Deletes a comment.
  Future<void> deleteComment(String momentId, String commentId) async {
    try {
      await _firestore.runTransaction((transaction) async {
        final momentRef = _momentsCollection.doc(momentId);
        final commentRef = momentRef.collection('comments').doc(commentId);

        transaction.delete(commentRef);
        transaction.update(momentRef, {'commentCount': FieldValue.increment(-1)});
      });
    } catch (e) {
      throw Exception('Failed to delete comment: $e');
    }
  }
}
