import 'package:chingu/models/notification_model.dart';
import 'package:chingu/models/user_model.dart';
import 'package:chingu/services/firestore_service.dart';
import 'package:chingu/services/notification_storage_service.dart';

/// 通知服務
/// 負責協調通知的生成與發送邏輯
class NotificationService {
  final NotificationStorageService _notificationStorageService;
  final FirestoreService _firestoreService;

  NotificationService({
    NotificationStorageService? notificationStorageService,
    FirestoreService? firestoreService,
  })  : _notificationStorageService =
            notificationStorageService ?? NotificationStorageService(),
        _firestoreService = firestoreService ?? FirestoreService();

  /// 發送配對通知給雙方
  Future<void> sendMatchNotifications({
    required String user1Id,
    required String user2Id,
  }) async {
    try {
      // 1. 獲取用戶資料
      final UserModel? user1 = await _firestoreService.getUser(user1Id);
      final UserModel? user2 = await _firestoreService.getUser(user2Id);

      if (user1 == null || user2 == null) {
        print('Error sending match notifications: one or both users not found.');
        return;
      }

      // 2. 構建並發送給 User 1 的通知 (告訴他跟 User 2 配對了)
      final notificationForUser1 = NotificationModel(
        id: '', // ID will be generated by Firestore
        userId: user1Id,
        type: 'match',
        title: '新配對成功! 🎉',
        message: '你與 ${user2.name} 配對成功了！快去打個招呼吧',
        imageUrl: user2.avatarUrl, // 使用對方的頭像
        actionType: 'open_chat',
        actionData: user2Id, // 傳遞對方 ID，以便跳轉
        isRead: false,
        createdAt: DateTime.now(),
      );

      await _notificationStorageService.sendNotificationToUser(
        user1Id,
        notificationForUser1,
      );

      // 3. 構建並發送給 User 2 的通知 (告訴他跟 User 1 配對了)
      final notificationForUser2 = NotificationModel(
        id: '',
        userId: user2Id,
        type: 'match',
        title: '新配對成功! 🎉',
        message: '你與 ${user1.name} 配對成功了！快去打個招呼吧',
        imageUrl: user1.avatarUrl, // 使用對方的頭像
        actionType: 'open_chat',
        actionData: user1Id,
        isRead: false,
        createdAt: DateTime.now(),
      );

      await _notificationStorageService.sendNotificationToUser(
        user2Id,
        notificationForUser2,
      );

      print('Match notifications sent to $user1Id and $user2Id');
    } catch (e) {
      print('Error sending match notifications: $e');
      // 不拋出異常，以免中斷配對流程
    }
  }
}
