// Mocks generated by Mockito 5.4.6 from annotations
// in chingu/test/services/dinner_event_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:chingu/models/notification_model.dart' as _i4;
import 'package:chingu/services/notification_storage_service.dart' as _i2;
import 'package:cloud_firestore/cloud_firestore.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [NotificationStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationStorageService extends _i1.Mock
    implements _i2.NotificationStorageService {
  MockNotificationStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> saveNotification(_i4.NotificationModel? notification) =>
      (super.noSuchMethod(
            Invocation.method(#saveNotification, [notification]),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#saveNotification, [notification]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<void> saveNotifications(
    List<_i4.NotificationModel>? notifications,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveNotifications, [notifications]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.NotificationModel>> getNotifications({
    int? limit = 20,
    _i6.DocumentSnapshot<Object?>? startAfter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getNotifications, [], {
              #limit: limit,
              #startAfter: startAfter,
            }),
            returnValue: _i3.Future<List<_i4.NotificationModel>>.value(
              <_i4.NotificationModel>[],
            ),
          )
          as _i3.Future<List<_i4.NotificationModel>>);

  @override
  _i3.Future<List<_i4.NotificationModel>> getUnreadNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#getUnreadNotifications, []),
            returnValue: _i3.Future<List<_i4.NotificationModel>>.value(
              <_i4.NotificationModel>[],
            ),
          )
          as _i3.Future<List<_i4.NotificationModel>>);

  @override
  _i3.Future<int> getUnreadCount() =>
      (super.noSuchMethod(
            Invocation.method(#getUnreadCount, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> markAsRead(String? notificationId) =>
      (super.noSuchMethod(
            Invocation.method(#markAsRead, [notificationId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> markAllAsRead() =>
      (super.noSuchMethod(
            Invocation.method(#markAllAsRead, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteNotification(String? notificationId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNotification, [notificationId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAllNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllNotifications, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int> deleteOldNotifications({int? olderThanDays = 30}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteOldNotifications, [], {
              #olderThanDays: olderThanDays,
            }),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Stream<List<_i4.NotificationModel>> watchNotifications({
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchNotifications, [], {#limit: limit}),
            returnValue: _i3.Stream<List<_i4.NotificationModel>>.empty(),
          )
          as _i3.Stream<List<_i4.NotificationModel>>);

  @override
  _i3.Stream<int> watchUnreadCount() =>
      (super.noSuchMethod(
            Invocation.method(#watchUnreadCount, []),
            returnValue: _i3.Stream<int>.empty(),
          )
          as _i3.Stream<int>);

  @override
  _i3.Future<List<_i4.NotificationModel>> getNotificationsByType(
    String? type,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationsByType, [type]),
            returnValue: _i3.Future<List<_i4.NotificationModel>>.value(
              <_i4.NotificationModel>[],
            ),
          )
          as _i3.Future<List<_i4.NotificationModel>>);

  @override
  _i3.Future<void> createSystemNotification({
    required String? title,
    required String? message,
    String? imageUrl,
    String? actionType,
    String? actionData,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createSystemNotification, [], {
              #title: title,
              #message: message,
              #imageUrl: imageUrl,
              #actionType: actionType,
              #actionData: actionData,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> createMatchNotification({
    required String? matchedUserName,
    required String? matchedUserId,
    String? matchedUserPhotoUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createMatchNotification, [], {
              #matchedUserName: matchedUserName,
              #matchedUserId: matchedUserId,
              #matchedUserPhotoUrl: matchedUserPhotoUrl,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> createEventNotification({
    required String? eventId,
    required String? eventTitle,
    required String? message,
    String? imageUrl,
    String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createEventNotification, [], {
              #eventId: eventId,
              #eventTitle: eventTitle,
              #message: message,
              #imageUrl: imageUrl,
              #userId: userId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> createMessageNotification({
    required String? senderName,
    required String? senderId,
    required String? messagePreview,
    String? senderPhotoUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createMessageNotification, [], {
              #senderName: senderName,
              #senderId: senderId,
              #messagePreview: messagePreview,
              #senderPhotoUrl: senderPhotoUrl,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
