// Mocks generated by Mockito 5.4.6 from annotations
// in chingu/test/services/matching_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:chingu/models/user_model.dart' as _i4;
import 'package:chingu/services/chat_service.dart' as _i5;
import 'package:chingu/services/firestore_service.dart' as _i2;
import 'package:chingu/services/notification_service.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FirestoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreService extends _i1.Mock implements _i2.FirestoreService {
  MockFirestoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> createUser(_i4.UserModel? userModel) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [userModel]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.UserModel?> getUser(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [uid]),
            returnValue: _i3.Future<_i4.UserModel?>.value(),
          )
          as _i3.Future<_i4.UserModel?>);

  @override
  _i3.Future<void> updateUser(String? uid, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [uid, data]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteUser(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [uid]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> userExists(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#userExists, [uid]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Stream<_i4.UserModel?> getUserStream(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getUserStream, [uid]),
            returnValue: _i3.Stream<_i4.UserModel?>.empty(),
          )
          as _i3.Stream<_i4.UserModel?>);

  @override
  _i3.Future<void> updateLastLogin(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastLogin, [uid]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.UserModel>> queryMatchingUsers({
    required String? city,
    int? budgetRange,
    String? gender,
    int? minAge,
    int? maxAge,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#queryMatchingUsers, [], {
              #city: city,
              #budgetRange: budgetRange,
              #gender: gender,
              #minAge: minAge,
              #maxAge: maxAge,
              #limit: limit,
            }),
            returnValue: _i3.Future<List<_i4.UserModel>>.value(
              <_i4.UserModel>[],
            ),
          )
          as _i3.Future<List<_i4.UserModel>>);

  @override
  _i3.Future<List<_i4.UserModel>> getBatchUsers(List<String>? uids) =>
      (super.noSuchMethod(
            Invocation.method(#getBatchUsers, [uids]),
            returnValue: _i3.Future<List<_i4.UserModel>>.value(
              <_i4.UserModel>[],
            ),
          )
          as _i3.Future<List<_i4.UserModel>>);

  @override
  _i3.Future<List<_i4.UserModel>> searchUsers(
    String? searchTerm, {
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchUsers, [searchTerm], {#limit: limit}),
            returnValue: _i3.Future<List<_i4.UserModel>>.value(
              <_i4.UserModel>[],
            ),
          )
          as _i3.Future<List<_i4.UserModel>>);

  @override
  _i3.Future<void> updateUserStats(
    String? uid, {
    int? totalDinners,
    int? totalMatches,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateUserStats,
              [uid],
              {#totalDinners: totalDinners, #totalMatches: totalMatches},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateUserRating(String? uid, double? newRating) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserRating, [uid, newRating]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> submitUserReport({
    required String? reporterId,
    required String? reportedUserId,
    required String? reason,
    required String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#submitUserReport, [], {
              #reporterId: reporterId,
              #reportedUserId: reportedUserId,
              #reason: reason,
              #description: description,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [ChatService].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatService extends _i1.Mock implements _i5.ChatService {
  MockChatService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> createChatRoom(String? user1Id, String? user2Id) =>
      (super.noSuchMethod(
            Invocation.method(#createChatRoom, [user1Id, user2Id]),
            returnValue: _i3.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#createChatRoom, [user1Id, user2Id]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<void> sendMessage({
    required String? chatRoomId,
    required String? senderId,
    required String? senderName,
    String? senderAvatarUrl,
    required String? message,
    String? type = 'text',
    bool? isForwarded = false,
    String? originalSenderId,
    String? originalSenderName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [], {
              #chatRoomId: chatRoomId,
              #senderId: senderId,
              #senderName: senderName,
              #senderAvatarUrl: senderAvatarUrl,
              #message: message,
              #type: type,
              #isForwarded: isForwarded,
              #originalSenderId: originalSenderId,
              #originalSenderName: originalSenderName,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i7.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> sendMatchNotification(String? user1Id, String? user2Id) =>
      (super.noSuchMethod(
            Invocation.method(#sendMatchNotification, [user1Id, user2Id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
