// Mocks generated by Mockito 5.4.6 from annotations
// in chingu/test/services/matching_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:chingu/models/notification_model.dart' as _i9;
import 'package:chingu/models/user_model.dart' as _i5;
import 'package:chingu/services/chat_service.dart' as _i6;
import 'package:chingu/services/firestore_service.dart' as _i3;
import 'package:chingu/services/notification_ab_service.dart' as _i2;
import 'package:chingu/services/notification_storage_service.dart' as _i10;
import 'package:chingu/services/rich_notification_service.dart' as _i8;
import 'package:cloud_firestore/cloud_firestore.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeNotificationContent_0 extends _i1.SmartFake
    implements _i2.NotificationContent {
  _FakeNotificationContent_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FirestoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreService extends _i1.Mock implements _i3.FirestoreService {
  MockFirestoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> createUser(_i5.UserModel? userModel) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [userModel]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i5.UserModel?> getUser(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [uid]),
            returnValue: _i4.Future<_i5.UserModel?>.value(),
          )
          as _i4.Future<_i5.UserModel?>);

  @override
  _i4.Future<void> updateUser(String? uid, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [uid, data]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteUser(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [uid]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> userExists(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#userExists, [uid]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Stream<_i5.UserModel?> getUserStream(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getUserStream, [uid]),
            returnValue: _i4.Stream<_i5.UserModel?>.empty(),
          )
          as _i4.Stream<_i5.UserModel?>);

  @override
  _i4.Future<void> updateLastLogin(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastLogin, [uid]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.UserModel>> queryMatchingUsers({
    required String? city,
    int? budgetRange,
    String? gender,
    int? minAge,
    int? maxAge,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#queryMatchingUsers, [], {
              #city: city,
              #budgetRange: budgetRange,
              #gender: gender,
              #minAge: minAge,
              #maxAge: maxAge,
              #limit: limit,
            }),
            returnValue: _i4.Future<List<_i5.UserModel>>.value(
              <_i5.UserModel>[],
            ),
          )
          as _i4.Future<List<_i5.UserModel>>);

  @override
  _i4.Future<List<_i5.UserModel>> getBatchUsers(List<String>? uids) =>
      (super.noSuchMethod(
            Invocation.method(#getBatchUsers, [uids]),
            returnValue: _i4.Future<List<_i5.UserModel>>.value(
              <_i5.UserModel>[],
            ),
          )
          as _i4.Future<List<_i5.UserModel>>);

  @override
  _i4.Future<List<_i5.UserModel>> searchUsers(
    String? searchTerm, {
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchUsers, [searchTerm], {#limit: limit}),
            returnValue: _i4.Future<List<_i5.UserModel>>.value(
              <_i5.UserModel>[],
            ),
          )
          as _i4.Future<List<_i5.UserModel>>);

  @override
  _i4.Future<void> updateUserStats(
    String? uid, {
    int? totalDinners,
    int? totalMatches,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateUserStats,
              [uid],
              {#totalDinners: totalDinners, #totalMatches: totalMatches},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateUserRating(String? uid, double? newRating) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserRating, [uid, newRating]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> submitUserReport({
    required String? reporterId,
    required String? reportedUserId,
    required String? reason,
    required String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#submitUserReport, [], {
              #reporterId: reporterId,
              #reportedUserId: reportedUserId,
              #reason: reason,
              #description: description,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [ChatService].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatService extends _i1.Mock implements _i6.ChatService {
  MockChatService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> createChatRoom(String? user1Id, String? user2Id) =>
      (super.noSuchMethod(
            Invocation.method(#createChatRoom, [user1Id, user2Id]),
            returnValue: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#createChatRoom, [user1Id, user2Id]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> sendMessage({
    required String? chatRoomId,
    required String? senderId,
    required String? senderName,
    String? senderAvatarUrl,
    required String? message,
    String? type = 'text',
    bool? isForwarded = false,
    String? originalSenderId,
    String? originalSenderName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [], {
              #chatRoomId: chatRoomId,
              #senderId: senderId,
              #senderName: senderName,
              #senderAvatarUrl: senderAvatarUrl,
              #message: message,
              #type: type,
              #isForwarded: isForwarded,
              #originalSenderId: originalSenderId,
              #originalSenderName: originalSenderName,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [RichNotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRichNotificationService extends _i1.Mock
    implements _i8.RichNotificationService {
  MockRichNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> showNotification(_i9.NotificationModel? notification) =>
      (super.noSuchMethod(
            Invocation.method(#showNotification, [notification]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [NotificationStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationStorageService extends _i1.Mock
    implements _i10.NotificationStorageService {
  MockNotificationStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> saveNotification(_i9.NotificationModel? notification) =>
      (super.noSuchMethod(
            Invocation.method(#saveNotification, [notification]),
            returnValue: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#saveNotification, [notification]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String> saveNotificationForUser(
    String? userId,
    _i9.NotificationModel? notification,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveNotificationForUser, [userId, notification]),
            returnValue: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#saveNotificationForUser, [
                  userId,
                  notification,
                ]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> saveNotifications(
    List<_i9.NotificationModel>? notifications,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveNotifications, [notifications]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i9.NotificationModel>> getNotifications({
    int? limit = 20,
    _i11.DocumentSnapshot<Object?>? startAfter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getNotifications, [], {
              #limit: limit,
              #startAfter: startAfter,
            }),
            returnValue: _i4.Future<List<_i9.NotificationModel>>.value(
              <_i9.NotificationModel>[],
            ),
          )
          as _i4.Future<List<_i9.NotificationModel>>);

  @override
  _i4.Future<List<_i9.NotificationModel>> getUnreadNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#getUnreadNotifications, []),
            returnValue: _i4.Future<List<_i9.NotificationModel>>.value(
              <_i9.NotificationModel>[],
            ),
          )
          as _i4.Future<List<_i9.NotificationModel>>);

  @override
  _i4.Future<int> getUnreadCount() =>
      (super.noSuchMethod(
            Invocation.method(#getUnreadCount, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> markAsRead(String? notificationId) =>
      (super.noSuchMethod(
            Invocation.method(#markAsRead, [notificationId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> markAllAsRead() =>
      (super.noSuchMethod(
            Invocation.method(#markAllAsRead, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteNotification(String? notificationId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNotification, [notificationId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAllNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllNotifications, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> deleteOldNotifications({int? olderThanDays = 30}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteOldNotifications, [], {
              #olderThanDays: olderThanDays,
            }),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Stream<List<_i9.NotificationModel>> watchNotifications({
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchNotifications, [], {#limit: limit}),
            returnValue: _i4.Stream<List<_i9.NotificationModel>>.empty(),
          )
          as _i4.Stream<List<_i9.NotificationModel>>);

  @override
  _i4.Stream<int> watchUnreadCount() =>
      (super.noSuchMethod(
            Invocation.method(#watchUnreadCount, []),
            returnValue: _i4.Stream<int>.empty(),
          )
          as _i4.Stream<int>);

  @override
  _i4.Future<List<_i9.NotificationModel>> getNotificationsByType(
    String? type,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationsByType, [type]),
            returnValue: _i4.Future<List<_i9.NotificationModel>>.value(
              <_i9.NotificationModel>[],
            ),
          )
          as _i4.Future<List<_i9.NotificationModel>>);

  @override
  _i4.Future<void> createSystemNotification({
    required String? title,
    required String? message,
    String? imageUrl,
    String? actionType,
    String? actionData,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createSystemNotification, [], {
              #title: title,
              #message: message,
              #imageUrl: imageUrl,
              #actionType: actionType,
              #actionData: actionData,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> createMatchNotification({
    required String? matchedUserName,
    required String? matchedUserId,
    String? matchedUserPhotoUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createMatchNotification, [], {
              #matchedUserName: matchedUserName,
              #matchedUserId: matchedUserId,
              #matchedUserPhotoUrl: matchedUserPhotoUrl,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> createEventNotification({
    required String? eventId,
    required String? eventTitle,
    required String? message,
    String? imageUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createEventNotification, [], {
              #eventId: eventId,
              #eventTitle: eventTitle,
              #message: message,
              #imageUrl: imageUrl,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> createMessageNotification({
    required String? senderName,
    required String? senderId,
    required String? messagePreview,
    String? senderPhotoUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createMessageNotification, [], {
              #senderName: senderName,
              #senderId: senderId,
              #messagePreview: messagePreview,
              #senderPhotoUrl: senderPhotoUrl,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [NotificationABService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationABService extends _i1.Mock
    implements _i2.NotificationABService {
  MockNotificationABService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ExperimentGroup getGroup(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getGroup, [userId]),
            returnValue: _i2.ExperimentGroup.control,
          )
          as _i2.ExperimentGroup);

  @override
  _i2.NotificationContent getContent(
    String? userId,
    _i2.NotificationType? type, {
    Map<String, dynamic>? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getContent, [userId, type], {#params: params}),
            returnValue: _FakeNotificationContent_0(
              this,
              Invocation.method(#getContent, [userId, type], {#params: params}),
            ),
          )
          as _i2.NotificationContent);
}
