// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4qmhoOnJHMIShd4RXVKSPsM8-pRXudxw',
    appId: '1:785159715135:web:YOUR_WEB_APP_ID',
    messagingSenderId: '785159715135',
    projectId: 'chingu-98387',
    authDomain: 'chingu-98387.firebaseapp.com',
    storageBucket: 'chingu-98387.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4qmhoOnJHMIShd4RXVKSPsM8-pRXudxw',
    appId: '1:785159715135:android:placeholder_id',
    messagingSenderId: '785159715135',
    projectId: 'chingu-98387',
    storageBucket: 'chingu-98387.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4qmhoOnJHMIShd4RXVKSPsM8-pRXudxw',
    appId: '1:785159715135:ios:ab0be06087b7b40eda3b8a',
    messagingSenderId: '785159715135',
    projectId: 'chingu-98387',
    storageBucket: 'chingu-98387.firebasestorage.app',
    iosBundleId: 'com.chriskid0824.chingu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4qmhoOnJHMIShd4RXVKSPsM8-pRXudxw',
    appId: '1:785159715135:ios:ab0be06087b7b40eda3b8a',
    messagingSenderId: '785159715135',
    projectId: 'chingu-98387',
    storageBucket: 'chingu-98387.firebasestorage.app',
    iosBundleId: 'com.chriskid0824.chingu',
  );
}

