// Mocks generated by Mockito 5.4.6 from annotations
// in chingu/test/screens/settings/feedback_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i11;
import 'dart:ui' as _i6;

import 'package:chingu/models/feedback_model.dart' as _i10;
import 'package:chingu/models/user_model.dart' as _i3;
import 'package:chingu/providers/auth_provider.dart' as _i4;
import 'package:chingu/services/feedback_service.dart' as _i9;
import 'package:cloud_firestore/cloud_firestore.dart' as _i8;
import 'package:firebase_auth/firebase_auth.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserMetadata_0 extends _i1.SmartFake implements _i2.UserMetadata {
  _FakeUserMetadata_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMultiFactor_1 extends _i1.SmartFake implements _i2.MultiFactor {
  _FakeMultiFactor_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIdTokenResult_2 extends _i1.SmartFake implements _i2.IdTokenResult {
  _FakeIdTokenResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserCredential_3 extends _i1.SmartFake
    implements _i2.UserCredential {
  _FakeUserCredential_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConfirmationResult_4 extends _i1.SmartFake
    implements _i2.ConfirmationResult {
  _FakeConfirmationResult_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_5 extends _i1.SmartFake implements _i2.User {
  _FakeUser_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDateTime_6 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserModel_7 extends _i1.SmartFake implements _i3.UserModel {
  _FakeUserModel_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i4.AuthProvider {
  @override
  _i4.AuthStatus get status =>
      (super.noSuchMethod(
            Invocation.getter(#status),
            returnValue: _i4.AuthStatus.uninitialized,
            returnValueForMissingStub: _i4.AuthStatus.uninitialized,
          )
          as _i4.AuthStatus);

  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<bool> register({
    required String? email,
    required String? password,
    required String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #email: email,
              #password: password,
              #name: name,
            }),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> updateUserData(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserData, [data]),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  bool hasCompletedOnboarding() =>
      (super.noSuchMethod(
            Invocation.method(#hasCompletedOnboarding, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<void> refreshUserData() =>
      (super.noSuchMethod(
            Invocation.method(#refreshUserData, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i1.Mock implements _i2.User {
  @override
  bool get emailVerified =>
      (super.noSuchMethod(
            Invocation.getter(#emailVerified),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isAnonymous =>
      (super.noSuchMethod(
            Invocation.getter(#isAnonymous),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i2.UserMetadata get metadata =>
      (super.noSuchMethod(
            Invocation.getter(#metadata),
            returnValue: _FakeUserMetadata_0(
              this,
              Invocation.getter(#metadata),
            ),
            returnValueForMissingStub: _FakeUserMetadata_0(
              this,
              Invocation.getter(#metadata),
            ),
          )
          as _i2.UserMetadata);

  @override
  List<_i2.UserInfo> get providerData =>
      (super.noSuchMethod(
            Invocation.getter(#providerData),
            returnValue: <_i2.UserInfo>[],
            returnValueForMissingStub: <_i2.UserInfo>[],
          )
          as List<_i2.UserInfo>);

  @override
  String get uid =>
      (super.noSuchMethod(
            Invocation.getter(#uid),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#uid)),
            returnValueForMissingStub: _i7.dummyValue<String>(
              this,
              Invocation.getter(#uid),
            ),
          )
          as String);

  @override
  _i2.MultiFactor get multiFactor =>
      (super.noSuchMethod(
            Invocation.getter(#multiFactor),
            returnValue: _FakeMultiFactor_1(
              this,
              Invocation.getter(#multiFactor),
            ),
            returnValueForMissingStub: _FakeMultiFactor_1(
              this,
              Invocation.getter(#multiFactor),
            ),
          )
          as _i2.MultiFactor);

  @override
  _i5.Future<void> delete() =>
      (super.noSuchMethod(
            Invocation.method(#delete, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getIdToken([bool? forceRefresh = false]) =>
      (super.noSuchMethod(
            Invocation.method(#getIdToken, [forceRefresh]),
            returnValue: _i5.Future<String?>.value(),
            returnValueForMissingStub: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<_i2.IdTokenResult> getIdTokenResult([
    bool? forceRefresh = false,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#getIdTokenResult, [forceRefresh]),
            returnValue: _i5.Future<_i2.IdTokenResult>.value(
              _FakeIdTokenResult_2(
                this,
                Invocation.method(#getIdTokenResult, [forceRefresh]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.IdTokenResult>.value(
              _FakeIdTokenResult_2(
                this,
                Invocation.method(#getIdTokenResult, [forceRefresh]),
              ),
            ),
          )
          as _i5.Future<_i2.IdTokenResult>);

  @override
  _i5.Future<_i2.UserCredential> linkWithCredential(
    _i2.AuthCredential? credential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithCredential, [credential]),
            returnValue: _i5.Future<_i2.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#linkWithCredential, [credential]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#linkWithCredential, [credential]),
              ),
            ),
          )
          as _i5.Future<_i2.UserCredential>);

  @override
  _i5.Future<_i2.UserCredential> linkWithProvider(_i2.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithProvider, [provider]),
            returnValue: _i5.Future<_i2.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#linkWithProvider, [provider]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#linkWithProvider, [provider]),
              ),
            ),
          )
          as _i5.Future<_i2.UserCredential>);

  @override
  _i5.Future<_i2.UserCredential> reauthenticateWithProvider(
    _i2.AuthProvider? provider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithProvider, [provider]),
            returnValue: _i5.Future<_i2.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#reauthenticateWithProvider, [provider]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#reauthenticateWithProvider, [provider]),
              ),
            ),
          )
          as _i5.Future<_i2.UserCredential>);

  @override
  _i5.Future<_i2.UserCredential> reauthenticateWithPopup(
    _i2.AuthProvider? provider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithPopup, [provider]),
            returnValue: _i5.Future<_i2.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#reauthenticateWithPopup, [provider]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#reauthenticateWithPopup, [provider]),
              ),
            ),
          )
          as _i5.Future<_i2.UserCredential>);

  @override
  _i5.Future<void> reauthenticateWithRedirect(_i2.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithRedirect, [provider]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.UserCredential> linkWithPopup(_i2.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithPopup, [provider]),
            returnValue: _i5.Future<_i2.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#linkWithPopup, [provider]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#linkWithPopup, [provider]),
              ),
            ),
          )
          as _i5.Future<_i2.UserCredential>);

  @override
  _i5.Future<void> linkWithRedirect(_i2.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithRedirect, [provider]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.ConfirmationResult> linkWithPhoneNumber(
    String? phoneNumber, [
    _i2.RecaptchaVerifier? verifier,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithPhoneNumber, [phoneNumber, verifier]),
            returnValue: _i5.Future<_i2.ConfirmationResult>.value(
              _FakeConfirmationResult_4(
                this,
                Invocation.method(#linkWithPhoneNumber, [
                  phoneNumber,
                  verifier,
                ]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.ConfirmationResult>.value(
              _FakeConfirmationResult_4(
                this,
                Invocation.method(#linkWithPhoneNumber, [
                  phoneNumber,
                  verifier,
                ]),
              ),
            ),
          )
          as _i5.Future<_i2.ConfirmationResult>);

  @override
  _i5.Future<_i2.UserCredential> reauthenticateWithCredential(
    _i2.AuthCredential? credential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithCredential, [credential]),
            returnValue: _i5.Future<_i2.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#reauthenticateWithCredential, [credential]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#reauthenticateWithCredential, [credential]),
              ),
            ),
          )
          as _i5.Future<_i2.UserCredential>);

  @override
  _i5.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> sendEmailVerification([
    _i2.ActionCodeSettings? actionCodeSettings,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#sendEmailVerification, [actionCodeSettings]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.User> unlink(String? providerId) =>
      (super.noSuchMethod(
            Invocation.method(#unlink, [providerId]),
            returnValue: _i5.Future<_i2.User>.value(
              _FakeUser_5(this, Invocation.method(#unlink, [providerId])),
            ),
            returnValueForMissingStub: _i5.Future<_i2.User>.value(
              _FakeUser_5(this, Invocation.method(#unlink, [providerId])),
            ),
          )
          as _i5.Future<_i2.User>);

  @override
  _i5.Future<void> updateEmail(String? newEmail) =>
      (super.noSuchMethod(
            Invocation.method(#updateEmail, [newEmail]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updatePassword(String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [newPassword]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updatePhoneNumber(
    _i2.PhoneAuthCredential? phoneCredential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhoneNumber, [phoneCredential]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateDisplayName(String? displayName) =>
      (super.noSuchMethod(
            Invocation.method(#updateDisplayName, [displayName]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updatePhotoURL(String? photoURL) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhotoURL, [photoURL]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateProfile({String? displayName, String? photoURL}) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #displayName: displayName,
              #photoURL: photoURL,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> verifyBeforeUpdateEmail(
    String? newEmail, [
    _i2.ActionCodeSettings? actionCodeSettings,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#verifyBeforeUpdateEmail, [
              newEmail,
              actionCodeSettings,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [UserModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserModel extends _i1.Mock implements _i3.UserModel {
  @override
  String get uid =>
      (super.noSuchMethod(
            Invocation.getter(#uid),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#uid)),
            returnValueForMissingStub: _i7.dummyValue<String>(
              this,
              Invocation.getter(#uid),
            ),
          )
          as String);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#name)),
            returnValueForMissingStub: _i7.dummyValue<String>(
              this,
              Invocation.getter(#name),
            ),
          )
          as String);

  @override
  String get email =>
      (super.noSuchMethod(
            Invocation.getter(#email),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#email),
            ),
            returnValueForMissingStub: _i7.dummyValue<String>(
              this,
              Invocation.getter(#email),
            ),
          )
          as String);

  @override
  int get age =>
      (super.noSuchMethod(
            Invocation.getter(#age),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  String get gender =>
      (super.noSuchMethod(
            Invocation.getter(#gender),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#gender),
            ),
            returnValueForMissingStub: _i7.dummyValue<String>(
              this,
              Invocation.getter(#gender),
            ),
          )
          as String);

  @override
  String get job =>
      (super.noSuchMethod(
            Invocation.getter(#job),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#job)),
            returnValueForMissingStub: _i7.dummyValue<String>(
              this,
              Invocation.getter(#job),
            ),
          )
          as String);

  @override
  List<String> get interests =>
      (super.noSuchMethod(
            Invocation.getter(#interests),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  String get country =>
      (super.noSuchMethod(
            Invocation.getter(#country),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#country),
            ),
            returnValueForMissingStub: _i7.dummyValue<String>(
              this,
              Invocation.getter(#country),
            ),
          )
          as String);

  @override
  String get city =>
      (super.noSuchMethod(
            Invocation.getter(#city),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#city)),
            returnValueForMissingStub: _i7.dummyValue<String>(
              this,
              Invocation.getter(#city),
            ),
          )
          as String);

  @override
  String get district =>
      (super.noSuchMethod(
            Invocation.getter(#district),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#district),
            ),
            returnValueForMissingStub: _i7.dummyValue<String>(
              this,
              Invocation.getter(#district),
            ),
          )
          as String);

  @override
  String get preferredMatchType =>
      (super.noSuchMethod(
            Invocation.getter(#preferredMatchType),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#preferredMatchType),
            ),
            returnValueForMissingStub: _i7.dummyValue<String>(
              this,
              Invocation.getter(#preferredMatchType),
            ),
          )
          as String);

  @override
  int get minAge =>
      (super.noSuchMethod(
            Invocation.getter(#minAge),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int get maxAge =>
      (super.noSuchMethod(
            Invocation.getter(#maxAge),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int get budgetRange =>
      (super.noSuchMethod(
            Invocation.getter(#budgetRange),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  bool get isActive =>
      (super.noSuchMethod(
            Invocation.getter(#isActive),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  DateTime get createdAt =>
      (super.noSuchMethod(
            Invocation.getter(#createdAt),
            returnValue: _FakeDateTime_6(this, Invocation.getter(#createdAt)),
            returnValueForMissingStub: _FakeDateTime_6(
              this,
              Invocation.getter(#createdAt),
            ),
          )
          as DateTime);

  @override
  DateTime get lastLogin =>
      (super.noSuchMethod(
            Invocation.getter(#lastLogin),
            returnValue: _FakeDateTime_6(this, Invocation.getter(#lastLogin)),
            returnValueForMissingStub: _FakeDateTime_6(
              this,
              Invocation.getter(#lastLogin),
            ),
          )
          as DateTime);

  @override
  String get subscription =>
      (super.noSuchMethod(
            Invocation.getter(#subscription),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#subscription),
            ),
            returnValueForMissingStub: _i7.dummyValue<String>(
              this,
              Invocation.getter(#subscription),
            ),
          )
          as String);

  @override
  int get totalDinners =>
      (super.noSuchMethod(
            Invocation.getter(#totalDinners),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int get totalMatches =>
      (super.noSuchMethod(
            Invocation.getter(#totalMatches),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  double get averageRating =>
      (super.noSuchMethod(
            Invocation.getter(#averageRating),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  bool get isTwoFactorEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#isTwoFactorEnabled),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String get twoFactorMethod =>
      (super.noSuchMethod(
            Invocation.getter(#twoFactorMethod),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#twoFactorMethod),
            ),
            returnValueForMissingStub: _i7.dummyValue<String>(
              this,
              Invocation.getter(#twoFactorMethod),
            ),
          )
          as String);

  @override
  String get budgetRangeText =>
      (super.noSuchMethod(
            Invocation.getter(#budgetRangeText),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#budgetRangeText),
            ),
            returnValueForMissingStub: _i7.dummyValue<String>(
              this,
              Invocation.getter(#budgetRangeText),
            ),
          )
          as String);

  @override
  String get genderText =>
      (super.noSuchMethod(
            Invocation.getter(#genderText),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#genderText),
            ),
            returnValueForMissingStub: _i7.dummyValue<String>(
              this,
              Invocation.getter(#genderText),
            ),
          )
          as String);

  @override
  String get preferredMatchTypeText =>
      (super.noSuchMethod(
            Invocation.getter(#preferredMatchTypeText),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#preferredMatchTypeText),
            ),
            returnValueForMissingStub: _i7.dummyValue<String>(
              this,
              Invocation.getter(#preferredMatchTypeText),
            ),
          )
          as String);

  @override
  Map<String, dynamic> toMap() =>
      (super.noSuchMethod(
            Invocation.method(#toMap, []),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i3.UserModel copyWith({
    String? name,
    String? email,
    int? age,
    String? gender,
    String? job,
    List<String>? interests,
    String? country,
    String? city,
    String? district,
    String? bio,
    String? avatarUrl,
    String? preferredMatchType,
    int? minAge,
    int? maxAge,
    int? budgetRange,
    bool? isActive,
    DateTime? lastLogin,
    _i8.GeoPoint? locationGeo,
    String? subscription,
    int? totalDinners,
    int? totalMatches,
    double? averageRating,
    bool? isTwoFactorEnabled,
    String? twoFactorMethod,
    String? phoneNumber,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#copyWith, [], {
              #name: name,
              #email: email,
              #age: age,
              #gender: gender,
              #job: job,
              #interests: interests,
              #country: country,
              #city: city,
              #district: district,
              #bio: bio,
              #avatarUrl: avatarUrl,
              #preferredMatchType: preferredMatchType,
              #minAge: minAge,
              #maxAge: maxAge,
              #budgetRange: budgetRange,
              #isActive: isActive,
              #lastLogin: lastLogin,
              #locationGeo: locationGeo,
              #subscription: subscription,
              #totalDinners: totalDinners,
              #totalMatches: totalMatches,
              #averageRating: averageRating,
              #isTwoFactorEnabled: isTwoFactorEnabled,
              #twoFactorMethod: twoFactorMethod,
              #phoneNumber: phoneNumber,
            }),
            returnValue: _FakeUserModel_7(
              this,
              Invocation.method(#copyWith, [], {
                #name: name,
                #email: email,
                #age: age,
                #gender: gender,
                #job: job,
                #interests: interests,
                #country: country,
                #city: city,
                #district: district,
                #bio: bio,
                #avatarUrl: avatarUrl,
                #preferredMatchType: preferredMatchType,
                #minAge: minAge,
                #maxAge: maxAge,
                #budgetRange: budgetRange,
                #isActive: isActive,
                #lastLogin: lastLogin,
                #locationGeo: locationGeo,
                #subscription: subscription,
                #totalDinners: totalDinners,
                #totalMatches: totalMatches,
                #averageRating: averageRating,
                #isTwoFactorEnabled: isTwoFactorEnabled,
                #twoFactorMethod: twoFactorMethod,
                #phoneNumber: phoneNumber,
              }),
            ),
            returnValueForMissingStub: _FakeUserModel_7(
              this,
              Invocation.method(#copyWith, [], {
                #name: name,
                #email: email,
                #age: age,
                #gender: gender,
                #job: job,
                #interests: interests,
                #country: country,
                #city: city,
                #district: district,
                #bio: bio,
                #avatarUrl: avatarUrl,
                #preferredMatchType: preferredMatchType,
                #minAge: minAge,
                #maxAge: maxAge,
                #budgetRange: budgetRange,
                #isActive: isActive,
                #lastLogin: lastLogin,
                #locationGeo: locationGeo,
                #subscription: subscription,
                #totalDinners: totalDinners,
                #totalMatches: totalMatches,
                #averageRating: averageRating,
                #isTwoFactorEnabled: isTwoFactorEnabled,
                #twoFactorMethod: twoFactorMethod,
                #phoneNumber: phoneNumber,
              }),
            ),
          )
          as _i3.UserModel);
}

/// A class which mocks [FeedbackService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeedbackService extends _i1.Mock implements _i9.FeedbackService {
  @override
  _i5.Future<void> submitFeedback(
    _i10.FeedbackModel? feedback,
    List<_i11.File>? images,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#submitFeedback, [feedback, images]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
